sigh3

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -9,50 +9,50 @@ env:
 
 
 jobs:
-  repocheck:
-    name: Check if repos are up to date
-    runs-on: ubuntu-20.04
-
-    outputs:
-      current: ${{ steps.check.outputs.current }}
-
-    steps:
-    - uses: actions/checkout@v2
-
-    - name: Wait for caching source
-      run: sleep 30
-
-    - uses: actions/cache@v2
-      with:
-        path: ~/id_file
-        key: helperid-${{ github.run_id }}
-
-    - name: Wait until repocheck in aux is complete
-      run: |
-        helper_id=$(cat ~/id_file)
-        cd ${{ github.workspace }}/tests/ci
-        jobs_url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/$helper_id/jobs
-        conclusion=$(echo $jobs_url | ./check_status.py completion "Repo check")
-        if [[ $conclusion == "failure" ]]; then
-          exit 1
-        fi
-
-    - uses: actions/cache@v2
-      with:
-        path: ~/repocheck_file
-        key: repocheck-${{ github.run_id }}
-
-    - name: Set repocheck currency flag
-      id: check
-      run: |
-        repocheck_result=$(cat ~/repocheck_file)
-        if [[ $repocheck_result == success ]]; then
-          echo "::set-output name=current::yes"
-        elif [[ $repocheck_result == failure ]]; then
-          echo "::set-output name=current::no"
-        fi
-
-
+#  repocheck:
+#    name: Check if repos are up to date
+#    runs-on: ubuntu-20.04
+#
+#    outputs:
+#      current: ${{ steps.check.outputs.current }}
+#
+#    steps:
+#    - uses: actions/checkout@v2
+#
+#    - name: Wait for caching source
+#      run: sleep 30
+#
+#    - uses: actions/cache@v2
+#      with:
+#        path: ~/id_file
+#        key: helperid-${{ github.run_id }}
+#
+#    - name: Wait until repocheck in aux is complete
+#      run: |
+#        helper_id=$(cat ~/id_file)
+#        cd ${{ github.workspace }}/tests/ci
+#        jobs_url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/$helper_id/jobs
+#        conclusion=$(echo $jobs_url | ./check_status.py completion "Repo check")
+#        if [[ $conclusion == "failure" ]]; then
+#          exit 1
+#        fi
+#
+#    - uses: actions/cache@v2
+#      with:
+#        path: ~/repocheck_file
+#        key: repocheck-${{ github.run_id }}
+#
+#    - name: Set repocheck currency flag
+#      id: check
+#      run: |
+#        repocheck_result=$(cat ~/repocheck_file)
+#        if [[ $repocheck_result == success ]]; then
+#          echo "::set-output name=current::yes"
+#        elif [[ $repocheck_result == failure ]]; then
+#          echo "::set-output name=current::no"
+#        fi
+#
+#
   runcheck:
     name: Check if run-ci is requested
     runs-on: ubuntu-20.04
@@ -87,7 +87,7 @@ jobs:
     name: Configure cases to run
     needs: [repocheck,runcheck]
     runs-on: ubuntu-20.04
-    if: needs.repocheck.outputs.current == 'yes' && needs.runcheck.outputs.cirun == 'yes'
+    if: needs.runcheck.outputs.cirun == 'yes'
 
     outputs:
       bld: ${{ steps.parse.outputs.bld }}
